'use strict';
console.log('comidas.js carregado');

window.BANCO_DE_COMIDAS = [
    // === CLÁSSICAS ===
    { nome: 'Pizza', icone: '🍕' },
    { nome: 'Hambúrguer', icone: '🍔' },
    { nome: 'Sushi', icone: '🍣' },
    { nome: 'Sorvete', icone: '🍦' },
    { nome: 'Taco', icone: '🌮' },
    { nome: 'Burrito', icone: '🌯' },
    { nome: 'Salada', icone: '🥗' },
    { nome: 'Frango Assado', icone: '🍗' },
    { nome: 'Espaguete', icone: '🍝' },
    { nome: 'Bolo', icone: '🍰' },
    { nome: 'Rosquinha', icone: '🍩' },
    { nome: 'Pipoca', icone: '🍿' },
    { nome: 'Batata Frita', icone: '🍟' },
    { nome: 'Cachorro Quente', icone: '🌭' },
    { nome: 'Lasanha', icone: '🍛' },
    { nome: 'Sopa Quente', icone: '🍜' },
    { nome: 'Arroz e Feijão', icone: '🍲' },
    { nome: 'Churrasco', icone: '🥩' },
    { nome: 'Camarão', icone: '🍤' },
    { nome: 'Panqueca', icone: '🥞' },
    { nome: 'Sanduíche', icone: '🥪' },
    { nome: 'Omelete', icone: '🍳' },
    { nome: 'Macarrão', icone: '🍝' },
    { nome: 'Feijoada', icone: '🍲' },
    { nome: 'Virado à Paulista', icone: '🍛' },
    { nome: 'Pão de Queijo', icone: '🧀' },
    { nome: 'Coxinha', icone: '🍗' },
    { nome: 'Pastel', icone: '🥟' },
    { nome: 'Empada', icone: '🥧' },
    { nome: 'Quibe', icone: '🥙' },
    { nome: 'Esfiha', icone: '🥙' },
    { nome: 'Shawarma', icone: '🌯' },
    { nome: 'Kebab', icone: '🥙' },
    { nome: 'Falafel', icone: '🧆' },
    { nome: 'Hummus', icone: '🥣' },
    { nome: 'Tabule', icone: '🥗' },
    { nome: 'Ceviche', icone: '🐟' },
    { nome: 'Tiradito', icone: '🐟' },
    { nome: 'Lomo Saltado', icone: '🥩' },
    { nome: 'Arroz Chaufa', icone: '🍚' },
    { nome: 'Cuscuz', icone: '🥣' },
    { nome: 'Tapioca', icone: '🫓' },
    { nome: 'Crepe', icone: '🥞' },
    { nome: 'Fondue', icone: '🫕' },
    { nome: 'Raclette', icone: '🧀' },
    { nome: 'Pierogi', icone: '🥟' },
    { nome: 'Dumpling', icone: '🥟' },
    { nome: 'Ramen', icone: '🍜' },
    { nome: 'Udon', icone: '🍜' },
    { nome: 'Tempura', icone: '🍤' },
    { nome: 'Yakitori', icone: '🍢' },
    { nome: 'Gyoza', icone: '🥟' },
    { nome: 'Onigiri', icone: '🍙' },
    { nome: 'Mochi', icone: '🍡' },
    { nome: 'Dango', icone: '🍡' },
    { nome: 'Takoyaki', icone: '🍢' },
    { nome: 'Okonomiyaki', icone: '🥞' },
    { nome: 'Bibimbap', icone: '🍚' },
    { nome: 'Kimchi', icone: '🥬' },
    { nome: 'Bulgogi', icone: '🥩' },
    { nome: 'Banh Mi', icone: '🥖' },
    { nome: 'Pho', icone: '🍜' },
    { nome: 'Spring Roll', icone: '🥙' },
    { nome: 'Pad Thai', icone: '🍜' },
    { nome: 'Tom Yum', icone: '🥘' },
    { nome: 'Green Curry', icone: '🍛' },
    { nome: 'Massaman Curry', icone: '🍛' },
    { nome: 'Nasi Goreng', icone: '🍚' },
    { nome: 'Mie Goreng', icone: '🍝' },
    { nome: 'Brigadeiro', icone: '🍫' },
    { nome: 'Açaí', icone: '🍧' },
    { nome: 'Strogonoff de Frango', icone: '🍛' },
    { nome: 'Pão de Alho', icone: '🧄' },
    { nome: 'Moqueca de Peixe', icone: '🥘' },
    { nome: 'Bobó de Camarão', icone: '🍤' },
    { nome: 'Pudim de Leite', icone: '🍮' },
    { nome: 'Bolinho de Chuva', icone: '🍩' },
    { nome: 'Escondidinho', icone: '🥧' },
    { nome: 'Omelete Recheado', icone: '🍳' },

    // === NOVAS COMIDAS TEMÁTICAS (Neon / Futuristas) ===
    { nome: 'Pizza Neon', icone: '🍕✨' },
    { nome: 'Hambúrguer Glow', icone: '🍔💡' },
    { nome: 'Sushi Cibernético', icone: '🍣🔮' },
    { nome: 'Sorvete de Laser', icone: '🍦⚡' },
    { nome: 'Taco Galáctico', icone: '🌮🚀' },
    { nome: 'Burrito Atômico', icone: '🌯☢️' },
    { nome: 'Salada de Plutônio', icone: '🥗💚' },
    { nome: 'Frango Robótico', icone: '🍗🤖' },
    { nome: 'Espaguete de Fótons', icone: '🍝💫' },
    { nome: 'Bolo de Néon', icone: '🍰🌈' },
    { nome: 'Rosquinha Estelar', icone: '🍩🌟' },
    { nome: 'Pipoca Quântica', icone: '🍿🌀' },
    { nome: 'Batata Frita Cósmica', icone: '🍟🌌' },
    { nome: 'Cachorro Quente Espacial', icone: '🌭🛸' },
    { nome: 'Lasanha de Dimensões', icone: '🍛🔷' },
    { nome: 'Sopa de Nêutrons', icone: '🍜⚛️' },
    { nome: 'Arroz de Buraco Negro', icone: '🍲🕳️' },
    { nome: 'Churrasco de Dragão', icone: '🥩🐉' },
    { nome: 'Camarão Cibernético', icone: '🍤💠' },
    { nome: 'Panqueca de Arco-Íris', icone: '🥞🌈' }
];

// ==================== RECEITAS ====================
window.RECEITAS = [
    // === GRÁTIS ===
    { id: 'rec-1', nome: 'Pizza Caseira', icone: '🍕', preco: 0, link: 'pizza.html' },
    { id: 'rec-2', nome: 'Hambúrguer Artesanal', icone: '🍔', preco: 0, link: 'hamburguer.html' },
    { id: 'rec-20', nome: 'Omelete Recheado', icone: '🍳', preco: 0, link: 'omelete-recheado.html' },
    { id: 'rec-21', nome: 'Salada Caesar', icone: '🥗', preco: 0, link: 'salada-caesar.html' },

    // === COM PREÇO ===
    { id: 'rec-3', nome: 'Sushi Maki', icone: '🍣', preco: 5, link: 'sushi.html' },
    { id: 'rec-4', nome: 'Churrasco na Brasa', icone: '🥩', preco: 10, link: 'churrasco.html' },
    { id: 'rec-5', nome: 'Feijoada Completa', icone: '🍲', preco: 8, link: 'feijoada.html' },
    { id: 'rec-6', nome: 'Ramen Tonkotsu', icone: '🍜', preco: 6, link: 'ramen.html' },
    { id: 'rec-7', nome: 'Tacos Mexicanos', icone: '🌮', preco: 4, link: 'tacos.html' },
    { id: 'rec-8', nome: 'Lasanha à Bolonhesa', icone: '🍛', preco: 7, link: 'lasanha.html' },
    { id: 'rec-9', nome: 'Ceviche Peruano', icone: '🐟', preco: 5, link: 'ceviche.html' },
    { id: 'rec-10', nome: 'Pão de Queijo Mineiro', icone: '🧀', preco: 2, link: 'pao-de-queijo.html' },
    { id: 'rec-11', nome: 'Sorvete de Chocolate', icone: '🍦', preco: 3, link: 'sorvete.html' },
    { id: 'rec-12', nome: 'Brigadeiro Gourmet', icone: '🍫', preco: 1, link: 'brigadeiro.html' },
    { id: 'rec-13', nome: 'Strogonoff de Frango', icone: '🍛', preco: 3, link: 'strogonoff.html' },
    { id: 'rec-14', nome: 'Pastel de Feira', icone: '🥟', preco: 2, link: 'pastel.html' },
    { id: 'rec-15', nome: 'Coxinha de Frango', icone: '🍗', preco: 4, link: 'coxinha.html' },
    { id: 'rec-16', nome: 'Pão de Alho Especial', icone: '🧄', preco: 2, link: 'pao-de-alho.html' },
    { id: 'rec-17', nome: 'Pudim de Leite', icone: '🍮', preco: 5, link: 'pudim.html' },
    { id: 'rec-18', nome: 'Moqueca de Peixe', icone: '🥘', preco: 6, link: 'moqueca.html' },

    // === NOVAS RECEITAS TEMÁTICAS ===
    { id: 'rec-22', nome: 'Pizza Neon Glow', icone: '🍕✨', preco: 12, link: 'pizza-neon.html' },
    { id: 'rec-23', nome: 'Hambúrguer Cósmico', icone: '🍔🚀', preco: 15, link: 'hamburguer-cosmico.html' },
    { id: 'rec-24', nome: 'Sushi de Dragão', icone: '🍣🐉', preco: 18, link: 'sushi-dragao.html' },
    { id: 'rec-25', nome: 'Taco Galáctico', icone: '🌮🌟', preco: 10, link: 'taco-galactico.html' },
    { id: 'rec-26', nome: 'Sorvete de Arco-Íris', icone: '🍦🌈', preco: 8, link: 'sorvete-arco-iris.html' },
    { id: 'rec-27', nome: 'Lasanha de Dimensões', icone: '🍛🌀', preco: 20, link: 'lasanha-dimensoes.html' },
    { id: 'rec-28', nome: 'Camarão Cibernético', icone: '🍤💠', preco: 14, link: 'camarao-cibernetico.html' },
    { id: 'rec-29', nome: 'Bolo de Néon', icone: '🍰🌈', preco: 9, link: 'bolo-neon.html' },
    { id: 'rec-30', nome: 'Panqueca Estelar', icone: '🥞🌌', preco: 7, link: 'panqueca-estelar.html' }
];