'use strict';
console.log('comidas.js carregado');

// ========================== BANCO DE COMIDAS EXPANDIDO (80 itens) ==========================
window.BANCO_DE_COMIDAS = [
    { nome: 'Pizza', icone: '🍕' }, { nome: 'Hambúrguer', icone: '🍔' },
    { nome: 'Sushi', icone: '🍣' }, { nome: 'Sorvete', icone: '🍦' },
    { nome: 'Taco', icone: '🌮' }, { nome: 'Burrito', icone: '🌯' },
    { nome: 'Salada', icone: '🥗' }, { nome: 'Frango Assado', icone: '🍗' },
    { nome: 'Espaguete', icone: '🍝' }, { nome: 'Bolo', icone: '🍰' },
    { nome: 'Rosquinha', icone: '🍩' }, { nome: 'Pipoca', icone: '🍿' },
    { nome: 'Batata Frita', icone: '🍟' }, { nome: 'Cachorro Quente', icone: '🌭' },
    { nome: 'Lasanha', icone: '🍛' }, { nome: 'Sopa Quente', icone: '🍜' },
    { nome: 'Arroz e Feijão', icone: '🍲' }, { nome: 'Churrasco', icone: '🥩' },
    { nome: 'Camarão', icone: '🍤' }, { nome: 'Panqueca', icone: '🥞' },
    { nome: 'Sanduíche', icone: '🥪' }, { nome: 'Omelete', icone: '🍳' },
    { nome: 'Ovo Frito', icone: '🍳' }, { nome: 'Macarrão', icone: '🍝' },
    { nome: 'Feijoada', icone: '🍲' }, { nome: 'Virado à Paulista', icone: '🍛' },
    { nome: 'Pão de Queijo', icone: '🧀' }, { nome: 'Coxinha', icone: '🍗' },
    { nome: 'Pastel', icone: '🥟' }, { nome: 'Empada', icone: '🥧' },
    { nome: 'Quibe', icone: '🥙' }, { nome: 'Esfiha', icone: '🥙' },
    { nome: 'Shawarma', icone: '🌯' }, { nome: 'Kebab', icone: '🥙' },
    { nome: 'Falafel', icone: '🧆' }, { nome: 'Hummus', icone: '🥣' },
    { nome: 'Tabule', icone: '🥗' }, { nome: 'Ceviche', icone: '🐟' },
    { nome: 'Tiradito', icone: '🐟' }, { nome: 'Lomo Saltado', icone: '🥩' },
    { nome: 'Arroz Chaufa', icone: '🍚' }, { nome: 'Cuscuz', icone: '🥣' },
    { nome: 'Tapioca', icone: '🫓' }, { nome: 'Crepe', icone: '🥞' },
    { nome: 'Fondue', icone: '🫕' }, { nome: 'Raclette', icone: '🧀' },
    { nome: 'Pierogi', icone: '🥟' }, { nome: 'Dumpling', icone: '🥟' },
    { nome: 'Ramen', icone: '🍜' }, { nome: 'Udon', icone: '🍜' },
    { nome: 'Tempura', icone: '🍤' }, { nome: 'Yakitori', icone: '🍢' },
    { nome: 'Gyoza', icone: '🥟' }, { nome: 'Onigiri', icone: '🍙' },
    { nome: 'Mochi', icone: '🍡' }, { nome: 'Dango', icone: '🍡' },
    { nome: 'Takoyaki', icone: '🍢' }, { nome: 'Okonomiyaki', icone: '🥞' },
    { nome: 'Bibimbap', icone: '🍚' }, { nome: 'Kimchi', icone: '🥬' },
    { nome: 'Bulgogi', icone: '🥩' }, { nome: 'Banh Mi', icone: '🥖' },
    { nome: 'Pho', icone: '🍜' }, { nome: 'Spring Roll', icone: '🥙' },
    { nome: 'Pad Thai', icone: '🍜' }, { nome: 'Tom Yum', icone: '🥘' },
    { nome: 'Green Curry', icone: '🍛' }, { nome: 'Massaman Curry', icone: '🍛' },
    { nome: 'Nasi Goreng', icone: '🍚' }, { nome: 'Mie Goreng', icone: '🍝' },
    { nome: 'Brigadeiro', icone: '🍫' }, { nome: 'Açaí', icone: '🍧' },
    { nome: 'Strogonoff de Frango', icone: '🍛' }, { nome: 'Pão de Alho', icone: '🧄' },
    { nome: 'Moqueca de Peixe', icone: '🥘' }, { nome: 'Bobó de Camarão', icone: '🍤' },
    { nome: 'Pudim de Leite', icone: '🍮' }, { nome: 'Bolinho de Chuva', icone: '🍩' },
    { nome: 'Escondidinho', icone: '🥧' }, { nome: 'Omelete Recheado', icone: '🍳' }
];

// ========================== RECEITAS EXPANDIDAS (20 itens) ==========================
window.RECEITAS = [
    { id: 'rec-1', nome: 'Pizza Caseira', icone: '🍕', preco: 0, link: 'pizza.html' },
    { id: 'rec-2', nome: 'Hambúrguer Artesanal', icone: '🍔', preco: 0, link: 'hamburguer.html' },
    { id: 'rec-3', nome: 'Sushi Maki', icone: '🍣', preco: 5, link: 'sushi.html' },
    { id: 'rec-4', nome: 'Salada Caesar', icone: '🥗', preco: 2, link: 'salada-caesar.html' },
    { id: 'rec-5', nome: 'Churrasco na Brasa', icone: '🥩', preco: 10, link: 'churrasco.html' },
    { id: 'rec-6', nome: 'Feijoada Completa', icone: '🍲', preco: 8, link: 'feijoada.html' },
    { id: 'rec-7', nome: 'Ramen Tonkotsu', icone: '🍜', preco: 6, link: 'ramen.html' },
    { id: 'rec-8', nome: 'Tacos Mexicanos', icone: '🌮', preco: 4, link: 'tacos.html' },
    { id: 'rec-9', nome: 'Lasanha à Bolonhesa', icone: '🍛', preco: 7, link: 'lasanha.html' },
    { id: 'rec-10', nome: 'Ceviche Peruano', icone: '🐟', preco: 5, link: 'ceviche.html' },
    { id: 'rec-11', nome: 'Pão de Queijo Mineiro', icone: '🧀', preco: 2, link: 'pao-de-queijo.html' },
    { id: 'rec-12', nome: 'Sorvete de Chocolate', icone: '🍦', preco: 3, link: 'sorvete.html' },
    { id: 'rec-13', nome: 'Brigadeiro Gourmet', icone: '🍫', preco: 1, link: 'brigadeiro.html' },
    { id: 'rec-14', nome: 'Strogonoff de Frango', icone: '🍛', preco: 3, link: 'strogonoff.html' },
    { id: 'rec-15', nome: 'Pastel de Feira', icone: '🥟', preco: 2, link: 'pastel.html' },
    { id: 'rec-16', nome: 'Coxinha de Frango', icone: '🍗', preco: 4, link: 'coxinha.html' },
    { id: 'rec-17', nome: 'Pão de Alho Especial', icone: '🧄', preco: 2, link: 'pao-de-alho.html' },
    { id: 'rec-18', nome: 'Pudim de Leite', icone: '🍮', preco: 5, link: 'pudim.html' },
    { id: 'rec-19', nome: 'Moqueca de Peixe', icone: '🥘', preco: 6, link: 'moqueca.html' },
    { id: 'rec-20', nome: 'Omelete Recheado', icone: '🍳', preco: 0, link: 'omelete-recheado.html' }
];
